# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# jobs
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello"
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  # jira support
  jira: circleci/jira@1.3.1
# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
