jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello"
orbs:
  jira: circleci/jira@1.3.1
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify:
                issue_regexp: '[A-Z]{2,30}[0-9]-[0-9]+'
